name: deploy

on:
  # Triggers the workflow on push or pull request events but only for 
  # the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run 
# sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as 
    # part of the job
    steps:
      # Checks-out your repository so your job can access it
      - name: Check-out repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '>= 3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

      # Run pytest with coverage
      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report=term --cov-branch

  deploy:
    permissions:
      id-token:
      contents:
    # Only run this job if the "ci" job passes
    needs: build

    # Only run this job if new work is pushed to "main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      # Set Up Python
      - name: Set up Python
        uses: actions/setup-python@v4


